
language: c

compiler:
  - clang
  - gcc

os:
  - linux

sudo: false

env:
  global:
    - MAKEJOBS=-j3
    - RUN_TESTS=true
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out

cache:
  apt: true

addons:
  apt:
    packages:
      - libssl-dev
      - libcurl4-openssl-dev
      - libjansson-dev
      - pkg-config

before_script:
  - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
  - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh

script:
  - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
  - CPUMINER_CONFIG_ALL="--prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
  - ./configure --cache-file=config.cache $CPUMINER_CONFIG_ALL $CPUMINER_CONFIG || ( cat config.log && false)
  - make -s $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL ; false )
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
  - if [ "$RUN_TESTS" = "true" ]; then make $MAKEJOBS distcheck; fi

